### PR TITLE
Some simplifications

### PR DESCRIPTION
**Pull request by jkuipers**
Hi,

nice example! I had a look, and you're configuring a root context with the same beans as the DispatcherServlet context. That's pointless, so you can simply remove that code. Also, there's no need to inject the result of an @Bean method in a field in the same class: you can simply invoke the method. That still preserves proper singleton behavior, because Spring will create a CGLib proxy that overrides every @Bean method (for exactly this purpose). I took the liberty of making these changes for you, so if you accept this pull request then you'll have these changes immediately.

### CODE REVIEW

**Comment by sdeleuze** [comment]
Thanks for these improvements !

**Comment by sdeleuze** [comment]
In order to make this even simpler, do you know if it is possible to implement a registry.addResourceHandler() that would handle all requests that are not in "/api/*" instead of the current code ?

There is also a solution where I could put all my static resources in a "/resources" and specify registry.addResourceHandler("/resources/*"), but I usually avoid to add an uneeded directory at the root of my Javascript apps ...

**Comment by jkuipers** [comment]
Sorry for the late response, I didn't see your question before. AFAIK you can simply use `registry.addResourceHandler("**").addResourceLocations("/");` to add all of them: this mapping will always have a lower priority than that for `@RequestMapping`-annoted methods, so it won't get in the way of your regular controllers.

**Comment by sdeleuze** [comment]
You're welcome. Thnaks for the tip, I have simplified the sample.

**Pull request merged**
